import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import CardContents from "../components/CardContents";
import SampleButton from "../components/SampleButton";
import * as styles from '../styles/home.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <CardContents/>
      </main>
      <SampleButton title={'TEST'} kind={'primary'}/>
      <Footer/>
    </div>
  )
}

export default Home
